Converting app to use configmgmt/secrets.env

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,36 +1,32 @@
-#!/usr/bin/env ruby
-require 'fileutils'
-include FileUtils
+#!/bin/bash
 
-# path to your application root.
-APP_ROOT = File.expand_path('..', __dir__)
+PURPLE='\033[0;35m'
+NC='\033[0m' # No Color
 
-def system!(*args)
-  system(*args) || abort("\n== Command #{args} failed ==")
-end
+fail() {
+    echo -e "Error: $@"
+    exit 1
+}
 
-chdir APP_ROOT do
-  # This script is a starting point to setup your application.
-  # Add necessary setup steps to this file.
+if [ -x "$(command -v secretmgmt)" ] ; then
+  configmgmt export-context --context cti_development > config/secrets.env
+else
+  echo "Configmgmt is not installed. Please follow install instructions at https://github.com/callrail/configmgmt then re-run this script." && exit 1
+fi
 
-  puts '== Installing dependencies =='
-  system! 'gem install bundler --conservative'
-  system('bundle check') || system!('bundle install')
+# install dependencies
+echo "${PURPLE}Installing gems and Node packages...${NC}"
+gem install bundler --conservative
+bundle install
 
-  # Install JavaScript dependencies if using Yarn
-  # system('bin/yarn')
+# ensure redis and postgres are running
+echo "${PURPLE}Ensuring Redis and Postgres are running...${NC}"
+[ -z "$(pgrep redis)" ] && redis-server &
+[ -z "$(pgrep postgres)" ] && pg_ctl start -D /usr/local/var/postgresql@9.5 -l /usr/local/var/postgresql@9.5/server.log
 
-  # puts "\n== Copying sample files =="
-  # unless File.exist?('config/database.yml')
-  #   cp 'config/database.yml.sample', 'config/database.yml'
-  # end
 
-  puts "\n== Preparing database =="
-  system! 'bin/rails db:setup'
+# db setup
+bundle exec rake db:create
+bundle exec rake db:reset
 
-  puts "\n== Removing old logs and tempfiles =="
-  system! 'bin/rails log:clear tmp:clear'
-
-  puts "\n== Restarting application server =="
-  system! 'bin/rails restart'
-end
+bin/rails log:clear tmp:clear
